services:
  backend:
    build:
      context: ./backend
      target: deploy
    container_name: backend
    ports:
      - 8080:8080

  backend-dev:
    build:
      context: ./backend
      target: debug
    ports:
      - 8081:8080
    container_name: backend-dev
    volumes:
      - ./backend:/app
    environment:
      - CGO_ENABLED=0

  sidecar:
    build:
      context: ./sidecar
      target: deploy
    container_name: sidecar
    depends_on:
      - backend
      - redis
    ports:
      # Will listen to 8000 port on local machine
      - 8000:8080
      - 8070:8070
    environment:
      - MY_ENV=local
      - GIN_MODE=release

  sidecar-dev:
    build:
      context: ./sidecar
      target: debug
    ports:
      - 8001:8080
      - 8070:8070
    container_name: sidecar-dev
    depends_on:
      - backend-dev
      - redis
    volumes:
      - ./sidecar:/app
    environment:
      - CGO_ENABLED=0
      - MY_ENV=local-dev

  redis:
    image: redis:8.0-alpine3.21

  functional-tests:
    build:
      context: ./tests/functional
    container_name: functional-tests
    depends_on:
      - backend
      - sidecar
      - redis
    # command: ["tail", "-f", "/dev/null"]
