services:
  backend:
    build:
      context: ./backend
      target: deploy
    container_name: backend
    ports:
      - 8080:8080

  backend-dev:
    build:
      context: ./backend
      target: debug
    ports:
      - 8081:8080
    container_name: backend-dev
    volumes:
      - ./backend:/app
    environment:
      - CGO_ENABLED=0

  sidecar:
    build:
      context: ./sidecar
      target: deploy
    container_name: sidecar
    depends_on:
      - backend
    ports:
      # Will listen to 8000 port on local machine
      - 8000:8080

  sidecar-dev:
    build:
      context: ./sidecar
      target: debug
    ports:
      - 8001:8080
    container_name: sidecar-dev
    depends_on:
      - backend-dev
    volumes:
      - ./sidecar:/app
    environment:
      - CGO_ENABLED=0